### ISSUE TITLE
Timeout not detected

### ISSUE THREAD

**Issue by reykjavikingur** [baalexander/node-portscanner#24]
In the function "checkPortStatus" there is an issue with the timeout handler. If a port is unused but my system cannot determine the port's status before the timeout (whatever that happens to be), the callback is never reached. This seems to be due to the fact that the "timeout" handler calls "socket.destroy()" which unfortunately prevents the automatic triggering of the "error" and "close" events. Basically, the timeout handler is causing the caller to hang indefinitely rather than responding with a timeout error to the callback.

**Comment by laggingreflex** [comment]
Related: #35

**Comment by laggingreflex** [comment]
Closing stale issues, please feel free to re-open if needed.
