### ISSUE TITLE
[Feature Request] Allow either IP address or domain

### ISSUE THREAD

**Issue by OmgImAlexis** [baalexander/node-portscanner#34]
I'm using this library to see if a service is online by converting the domain to an ip and then using port 80. It'd be handy if this library could check if the input is a ip, if it isn't then it'd either convert the domain to an ip and use that.

**Comment by laggingreflex** [comment]
I think this would be too much to ask from portscanner.

Please checkout [checkdns](https://www.npmjs.com/package/checkdns) or [check-domain](https://www.npmjs.com/package/check-domain).

**Comment by OmgImAlexis** [comment]
Just a quick example of how it could be added using the native dns package.

```
var dns = require('dns');
dns.lookup('google.com', function(err, address, family){
    console.log(address); // address = the first A record of google.com
});
```

**Comment by laggingreflex** [comment]
That certainly makes it seem easier that I had originally thought. Thanks for that. 

I've made some preliminary changes in an attempt to support this in #47. Please checkout locally and test it out if can.

I still have some concerns though. 

Would it still require identifying addresses and deciding which ones to lookup, or could we make **all** addresses go through `dns.lookup`, be it IP address (including IPv6) or domain names, and if so what might be the consequences? 

Could you suggest some tests for this scenario? I've only ever used portscanner in localhost machine context.
