### ISSUE TITLE
Timeout error is not handled correctly

### ISSUE THREAD

**Issue by elmccd** [baalexander/node-portscanner#35]
After timeout there is no Error thrown.
While using findAPortNotInUse the first provided port is returned as a 'free' despite fact it's not. After manually increasing timeout in source code return ports are correct.

``` js
    if(exception && !connectionRefused)
      error = exception;
    else
      error = null;
```

Else statement seems to suppress error which was set in socket's timeout event.

BTW There is no option to set timeout in interface.

**Comment by connection** [comment]
I'd also like to know about setting a timeout on the port scanner

**Comment by laggingreflex** [comment]
Isn't that the expected behavior?
```js
  // If no response, assume port is not listening // <<< 
  socket.setTimeout(timeout)
  socket.on('timeout', function () {
    status = 'closed'
    error = new Error('Timeout (' + timeout + 'ms) occurred waiting for ' + host + ':' + port + ' to be available')
    socket.destroy()
  })
```
If I increase the timeout to, say 60000, on a port such as `10.10.10.10:3000` it just keeps on waiting.

And without that else statement these tests are failing. (which you wrote btw, thanks for that:)
```
  × findAPortNotInUse - with array as parameter
  t.is(port, 3002)
       |
       false
  × findAPortNotInUse - start from taken port
  t.is(port, 3001)
       |
       false
  × checkPortStatus - free
  t.is(error, null)
       |
       Error{}
  × findAPortNotInUse - start from free port
  t.is(error, null)
       |
       Error{}
```

**Comment by laggingreflex** [comment]
Closing stale issues, please feel free to re-open if needed.
