### ISSUE TITLE
Update version of async

### ISSUE THREAD

**Issue by baderbuddy** [baalexander/node-portscanner#38]
This project relies on an out of date version of async, to keep current could you update the version of this dependency?

**Comment by baderbuddy** [comment]
I just realized there's already an open pull request with this change also.

**Comment by trishayy** [comment]
@shinnn Is this PR going to be merged in soon? I would like to be able to use library! =)

**Comment by laggingreflex** [comment]
Merged in https://github.com/baalexander/node-portscanner/commit/4c7a88436fcccb85982b4343138be74e6d01b3c6. Released a new minor version 1.1.0. Please check it out and let me know.
