### ISSUE TITLE
v1.1.0 doesn't work with grunt-contrib-connect

### ISSUE THREAD

**Issue by alippai** [baalexander/node-portscanner#49]
The last _portscanner_ release broke our _connect_ tasks saying "Fatal error: Port 443 is already in use by another process.".

**Comment by philtim** [comment]
We had the very same problem. Try changing your port number from a string to a number. The latest version now checks whether the params are of type number, string, or function and handles each one differently. Surely not a nice solution, but a quick workaround.

**Comment by laggingreflex** [comment]
I'm trying to hunt down what's causing the error, could you please let me know how you're using grunt-contrib-connect? I've ran its tests with portscanner 1.1.0 and they seem to be all passing.

**Comment by laggingreflex** [comment]
Thanks very much for the insight @philtim. Hopefully fixed now. See #51 for details
