### ISSUE TITLE
v1.1.0 breaks our usage of browser-sync

### ISSUE THREAD

**Issue by tbassetto** [baalexander/node-portscanner#50]
`[browser-sync](https://github.com/Browsersync/browser-sync)` depends on `portscanner ^1.0.0` so it now downloads 1.1.0. Is there a changelog available? Serving our app crashes (without a meaningful message) unless we force install `portscanner 1.0.0`. There must be a breaking change somewhere.

**Comment by laggingreflex** [comment]
Extremely sorry about introducing a breaking change in a minor version. 

I've reverted it to 1.0.0 which is now published as 1.1.1

The previous new version will now be published as 2.0.0

**Comment by laggingreflex** [comment]
I'm trying to reproduce the error, can you please let me know how you're using Browsersync?

**Comment by laggingreflex** [comment]
Hopefully fixed now. See #51 for details

**Comment by tbassetto** [comment]
Yes, `1.2.0` fixed the bug we were experiencing. Thanks!
