### ISSUE TITLE
Accept strings for ports?

### ISSUE THREAD

**Issue by laggingreflex** [baalexander/node-portscanner#52]
It seems some users might've depended on `portscanner` to accept strings as ports which caused the 1.1.0 to break their projects #49 #50 #51. It's since been fixed and breaking changes moved to v2.0.0

Should we stop supporting strings as ports? Or continue to do so and re-do the changes based on that? 

This can create a lot of work internally as well, like going through ranges in `findAPortNotInUse`: 

```js
portScanner.findAPortInUse(3000, '3010', '127.0.0.1', (error, port) => {...})
portScanner.findAPortInUse('3000', '3010', '127.0.0.1', (error, port) => {...})
portScanner.findAPortInUse('3000', '3010', '127.0.0.1', (error, port) => {...})
```
Not that someone would use it that way, but supporting this would mean handling these as well, right?

**Comment by philtim** [comment]
What about trying to parse it to an int. If it is not a number you will get a NaN and could differentiate it on that level?

**Comment by laggingreflex** [comment]
One change in particular was making some arguments, like "host" optional. Assuming ports would be numbers made it easy to just check for a string which would automatically be assumed to be the host.  `parseInt('127.0.0.0') = 127` so that can't work, we'd have to check the string for more stuff..

**Comment by laggingreflex** [comment]
[is-number-like](https://www.npmjs.com/package/is-number-like) looks promising. Should we use this?

**Comment by laggingreflex** [comment]
Welp,
