### ISSUE TITLE
For loop to scan an port through a subnet

### ISSUE THREAD

**Issue by speeduhh** [baalexander/node-portscanner#55]
Hi, when I try to scan an entire class in a for loop all works great and I get the async callbacks as intended but whit no way of telling from what IP from the subnet the callback is.
I modified in promisify.js on line 7 to add host and in portscanner.js on line 132 to add host and now the callback is called with (error, status, host). Could this be implemented?

**Comment by laggingreflex** [comment]
Hi there. Could you give a code example? I'm not sure I follow. Wouldn't the host be the same as the one you provided? `portscanner.checkPortStatus(3000, >> '127.0.0.1', << ...` (127xx by default). Feel free to also make a PR to elaborate further if needed.

**Comment by speeduhh** [comment]
Yes, sure, my bad I did not put the code the first time. I would like to run something like this and know on which HOST from the loop port 80 or 22 is opened, for example.
`
var portscanner = require('portscanner');
var callback = function(error, status) {
    console.log(status);
}

for (i = 0; i <= 10; i++) {
    var ip = "10.10.9." + i;
    portscanner.checkPortStatus(22, ip, callback);
}`

**Comment by laggingreflex** [comment]
This could be done without any modification to portscanner. 

```js
for (let i = 0; i <= 10; i++) {
  const ip = "10.10.9." + i;
  portscanner.checkPortStatus(22, ip, function(err, status){
    console.log(status, ip);  
    // or call your callback(err, status, ip)
  });
}
```

Be sure to use `let` and `const` instead of `var`

**Comment by speeduhh** [comment]
Thanks for the lesson, I owe you a beer!
